### ISSUE TITLE
Advertise both private and public IP as well

### ISSUE THREAD

**Issue by imredobos** [livekit/livekit#1111]
Livekit should advertise both private and public IP as well to have the opportunity to leverage network enhancements with the private IP and have the most of the connectivity with the public IP

**Comment by imredobos** [comment]
@davidzhao can we expect anything for this in the near future?

**Comment by davidzhao** [comment]
Hey @imredobos this has landed in v1.3.3, give it a shot and let us know if that works for you.

**Comment by imredobos** [comment]
hey @davidzhao, I did not manage to make it work. What configuration should be used to achieve this functionality?
Also, in my local environment, I've changed this line: https://github.com/livekit/livekit/blob/master/pkg/rtc/config.go#L245 by removing ```rtcConf.NodeIP == ""``` and the result is exactly what I want to see - private and public IP as well - with the configuration ```use_external_ip: false``` and ```use_ice_lite: false```.

**Comment by imredobos** [comment]
Not needed anymore

**Comment by ss14** [comment]
Was this resolved? I have not been able to make livekit-server advertise both public ip and private ip as ICE candidates. In my setup, I have browser clients (connecting over internet) and clients in the same vnet of the livekit-server. Setting `node_ip` with public ip forces even the "local clients" connect over the public ip instead of reachable private IP.

Details about my setup:
1. The livekit server and "local clients" are part of the same k8 cluster.
2. A loadbalancer with public IP sits in front of livekit server.
3. livekit server is v1.9.1

@davidzhao @imredobos
