### ISSUE TITLE
Question: Best way to save Data messages in DB

### ISSUE THREAD

**Issue by helderjbe** [livekit/livekit#1146]
I'm looking to implement a chat system that saves users' messages. To do this using LiveKit rooms, I'm using data messages (https://docs.livekit.io/client/data-messages/). However, I need to intercept these messages so that it's possible to save and moderate them.

Consider the following server instances (in the same region):
- LiveKit image
- REST API server
- CDN (client files)

Currently, this is what happens when a user sends a message in the room:
1- Send a request to my custom API server (not using p2p data messages from Livekit since I need to intercept them)
2- Call `await roomServiceClient.getParticipant(currentChatid, currentUserId);` (to check if the user is actually in the room)
3- Moderate and save the message to DB
4- Call `roomServiceClient.sendData(...)`
5- On the receiver side, call `roomState.room.on(RoomEvent.DataReceived, ...)`

**The problem with this approach is that it takes ~2s** on `await roomServiceClient.getParticipant`. Calling this every time a message is sent is clearly not efficient. My question is, how would you go about implementing this system? Any thoughts are greatly appreciated.

P.S.: Apologies if this is not the right place to post my question, I looked up on Stackoverflow but it doesn't seem that questions about LiveKit get answered there.

**Comment by davidzhao** [comment]
hey @helderjbe, is there a reason why you'd need to call `getParticipant` each time? Since you are calling your custom API server, is there a scenario that it's called when the participant is currently not in the room? I think skipping that step would greatly simplify this use case. I see two paths:

- save and use data messages from client:
  1. send request to your server to persist message
  2. at the same time, use `publishData` on the client to send a message to other participants
- use the current approach, but skip `getParticipant`

Also, are you using LiveKit Cloud? or hosting yourself? The 2s delay sounds abnormal.

**Comment by helderjbe** [comment]
> hey @helderjbe, is there a reason why you'd need to call `getParticipant` each time? Since you are calling your custom API server, is there a scenario that it's called when the participant is currently not in the room? I think skipping that step would greatly simplify this use case. I see two paths:

In my case I can't really trust the clients using the app, so the getParticipant part is to actually check if the user sending the message is in the room. Otherwise, some malicious user could simply use Postman (or simply curl) to make the request to my API server with chatId and userId and they could broadcast their messages to any room.

> * save and use data messages from client:
>   1. send request to your server to persist message
>   2. at the same time, use `publishData` on the client to send a message to other participants

Using the same reasoning above, couldn't a malicious user simply prevent either request from happening? This would create phantom messages.

> * use the current approach, but skip `getParticipant`

That would be the best, but since the requests are being made to my API instance instead of the LiveKit instance, I'm currently not seeing another way to check the participant status.

> Also, are you using LiveKit Cloud? or hosting yourself? The 2s delay sounds abnormal.

Yes, I thought so, maybe it was my setup here, I'll double-check it once again. I'm currently not using LiveKit cloud as I'm still beta testing, but I will definitely use it once I get everything right.

**Comment by davidzhao** [comment]
> the getParticipant part is to actually check if the user sending the message is in the room

I think it's probably better to pursue a mode of authentication so that you can "trust" the request sent by the client. If they can simulate the API call, it wouldn't be too complicated to simulate entering the room and publishing a message the same way.

one idea is to use JWT tokens, similar to livekit itself.

**Comment by helderjbe** [comment]
It will be a bit hard as in my use case users can register at will, but that's a good idea I can elaborate on. I will try and cook something up from that. Thank you!

Also, I just wanted to say that I love LiveKit, it's life-changing for a developer like myself. Wish you all the best!
