### ISSUE TITLE
service/ioinfo.go:83 egress failed 

### ISSUE THREAD

**Issue by anishmenon** [livekit/livekit#1700]
I'm failed to process Egress

2023-05-09T18:08:29.038Z ERROR livekit service/ioinfo.go:83 egress failed {"egressID": "EG_UcQJNTSqgxHT", "error": "could not establish signal connection"}
github.com/livekit/livekit-server/pkg/service.(*IOInfoService).UpdateEgressInfo
 /workspace/pkg/service/ioinfo.go:83
github.com/livekit/livekit-server/pkg/service.(*IOInfoService).egressWorkerDeprecated.func1
 /workspace/pkg/service/ioinfo.go:156

**Comment by davidzhao** [comment]
wrong repo and no information provided.

**Comment by anishmenon** [comment]
i've setup kubernetes cluster by following livekit official help documentation
and it pull the below image ( https://hub.docker.com/r/livekit/livekit-server) . So this error is happening when i request for egress track composite.

image:
  repository: livekit/livekit-server
  pullPolicy: IfNotPresent
 
When you blindly say wrong repo as the creator of Livekit. and closed this issue. ??

@davidzhao

**Comment by davidzhao** [comment]
You are having an issue with Egress. This repo is for the core livekit server.
Before filing an issue, please ensure you've configured it correctly, including making sure Egress could reach the server.

Additionally, if issues are opened without following bug report templates, they will be immediately closed because there isn't sufficient information for anyone to know what's going on.

**Comment by anishmenon** [comment]
This log is generated on Livekit-server pod.  I've followed the document and configured 

on Egress side 

ws_url: wss://MY_host
insecure: false
log_level: debug
api_key: XYZ
api_secret: XYZ


Bu the error happens when doing track composite from egress using livekit-cli
