### ISSUE TITLE
blur streaming sometimes 

### ISSUE THREAD

**Issue by crapthings** [livekit/livekit#1853]
js sdk client latest version
go livekit server, maybe 1.41 or 1.42

is this cause by these two options?

adaptiveStream: true,
dynacast: true,

i've already closed adaptiveStream: false, but seems not help

![image](https://github.com/livekit/livekit/assets/1147704/c43253fb-3b5d-4669-bad4-a37b95725ebc)
![image](https://github.com/livekit/livekit/assets/1147704/016c7732-4ccb-417c-8d04-ddf8903d9506)

**Comment by boks1971** [comment]
This could be due to congestion. Speed test results are not definitive proof of available bandwidth. One of the following could happen
1. the bandwidth estimation algorithm could have false negatives and that will results in server adjusting stream quality by picking a lower simulcast layer
2. Some other cross traffic could happen temporarily causing more jitter in media traffic flow (jitter more than raw bandwidth affects the bandwidth estimation).
3. Path between client <-> server has a bottle neck link where as speed test connection does not (typically these are picking the best server to test against).

**Comment by crapthings** [comment]
can i force not to use the lower layer?

**Comment by boks1971** [comment]
There could be multiple places
1. In the up stream direction, it is up to the client (browser or mobile client) to decide what it will publish based on available resources (bandwidth, CPU, etc.). So, the publisher could turn off higher resolution layers at any time based on conditions.
2. In the server, in the forwarding path, there  are a couple of things you can try
    1. [`enabled`](https://github.com/livekit/livekit/blob/919355c873a35afe3aa5e0fc3add2d17431d82ad/config-sample.yaml#L68) - simplest option, just turn off congestion control. 
    2. [`allow_pause`](https://github.com/livekit/livekit/blob/919355c873a35afe3aa5e0fc3add2d17431d82ad/config-sample.yaml#L71) - set this to `false` to not pause video streaming - `false` is the default (documentation needs to be updated for this)
    3.  [`min_channel_capacity`](https://github.com/livekit/livekit/blob/919355c873a35afe3aa5e0fc3add2d17431d82ad/pkg/config/config.go#L131) - not documented. It is just in code and is not used by anybody AFAIK. So, it may have some rough edges. You can use that to set a high value for available bandwidth in the down stream direction. This will fool the server into thinking it has that much bandwidth in the down stream direction and stream higher resolution layers. But, please note that congesting the channel could affect audio quality.
