### ISSUE TITLE
Is it possible to turn off DTLS?

### ISSUE THREAD

**Issue by shalom-aviv** [livekit/livekit#1979]
**Describe the bug**
Seems that some providers can block DTLS traffic

**Comment by davidzhao** [comment]
It's not possible. DTLS is mandatory in WebRTC ICE connections, but is not required in TURN/TLS.

Browsers should not block LiveKit traffic due to:
* We do use DTLS signatures that close match Chrome usage. see [discussion here](https://gitlab.torproject.org/tpo/anti-censorship/censorship-analysis/-/issues/40030#note_2804998)
* If DTLS/UDP is blocked, we do automatically fallback to TURN/TLS, which resembles typical TLS traffic
