### ISSUE TITLE
Wrong connnectionQuality state

### ISSUE THREAD

**Issue by AurimasG12** [livekit/livekit#2717]
**Describe the bug**
As user, I want to see correct network indicators.
Now as a local user, I can see my network indicator as having excellent connection quality, but others see three gray bars (unknown state). Sometimes state does not even change after mic/cam toggle to on and stays at unknown state.

![image](https://github.com/livekit/livekit/assets/51153447/75aedacb-f9a9-4847-ac97-ecb35e54f6d5)

**Server**
- Version: [1.6.1]
- Environment: [e.g. local dev, EKS] - meet.livekit.io meeting with their server.
- any other information about your deployment setup

**Client**
- SDK: [e.g. js, ios]
- Version: [0.x.x]

**To Reproduce**
1. Join meet.livekit.io meeting with participant A (turn off camera and microphone)
2. Join meet.livekit.io meeting with participant B (with camera on, mic on)
3. Check network indicators

**Expected behavior**
Indicators should appear with exact network quality

**Comment by lukasIO** [comment]
Comment with some of my findings: https://github.com/livekit/livekit/issues/2716#issuecomment-2112839311

**Comment by lukasIO** [comment]
While not ideal, it does work like intended today.
The reason is that the quality updates are scoped to participants that are subscribed to another participant’s track(s).
So if your local participant A doesn’t subscribe to any tracks from participant B, then it will never receive quality updates for B.
The local participant however receives quality updates for themselves.
