### ISSUE TITLE
WHEP support

### ISSUE THREAD

**Issue by lourd** [livekit/livekit#2811]
I'm migrating to LiveKit from SRS. My application's use case is focused on a single broadcasted video use case. That video's primarily forwarded to live video platforms over RTMP, but also consumed by users watching on a website.

SRS has WHEP support that I used for the aspect of users watching on a website. There's this closed issue about WHIP support that's of course has been fulfilled (working great so far!) https://github.com/livekit/livekit/issues/1083. I'm making this issue to re-request WHEP support.

Thanks!

**Comment by davidzhao** [comment]
that makes sense as an use case. It should be fairly straight forward to add WHEP support.

**Comment by lourd** [comment]
I've been using the player built into Oryx during development. The code for that is here:

https://github.com/ossrs/oryx/blob/main/platform/containers/www/players/whep.html
https://github.com/ossrs/oryx/blob/main/platform/containers/www/players/js/srs.sdk.js

As you can see, it's old school, it's es5 jquery. I haven't figured out what I should use for the WHEP client for my own product.

**Comment by davidzhao** [comment]
After a bit of research, it seems that WHEP is incompatible with LiveKit's connection models. WHEP expects the client to send an offer to the server, in order to negotiate that it's waiting to receive tracks. With LiveKit's connection model, the sender of tracks will be the one initiating the offer.

With those findings, we will not be able to offer WHEP support.
