### ISSUE TITLE
Multiple Room connections for identical user

### ISSUE THREAD

**Issue by konsalex** [livekit/livekit#3039]
**Describe the bug**

Not a bug, rather than a question around identical participants.

Is there a way to create multiple Room clients that can connect with the same user, but provide complementary streams (one room instance to handle audio and one video)?

An example this case is needed is for a video/audio sharing app (like TeamViewer) built with Tauri and multiple windows.

As there is no shared JS runtime between the windows, every window would need a room instance like for example:
```
<LiveKitRoom token={token} serverUrl={serverURL} connect={true}>
      <ConsumerComponent />
</LiveKitRoom>
```

![CleanShot 2024-09-23 at 23 48 23@2x](https://github.com/user-attachments/assets/2af3a446-0cbb-43cb-b35e-f68b959dd449)

That means that the window that shares audio will disconnect as soon as the publishing video window is created.

**Additional context**
Added a fair amount of context in the description, but can provide more if needed.

**Comment by davidzhao** [comment]
@konsalex with LiveKit's connection model, each participant is uniquely represented by an `identity`. We are not able to "join" multiple WebRTC participants into a single one.

the best way to handle this case is to join as two separate participants. The subscribers will have no problems subscribing to all of the tracks that are incoming. In fact, Google Meet uses this approach for screen shares (they appear as new participants)

**Comment by benbucksch** [comment]
I need this same feature. I would like the user to be able to connect with both PC and with the smartphone, and e.g. use the microphone of the smartphone and the camera of the PC, or vise versa, and use the monitor of the PC.

Why not 2 participants:
* Others participants should not see the same user twice participant.
* The video/speaking switching needs to work in unison. If the other participant uses a "speaker" view the automatically shows the speaking participant, that won't work, if my camera and microphone come from different "participants".

That's why the feature to join one user with 2 devices into a single participants is needed.

What I image is that both devices use the same "identity".
