### ISSUE TITLE
Max users per room. Limit increase.

### ISSUE THREAD

**Issue by denisov-k** [livekit/livekit#3041]
The official documentation (https://docs.livekit.io/home/get-started/intro-to-livekit/) says that the self-hosted version has a limit of 3000 users in a room. What is the reason for this limitation? Is there any way to bypass it?

**Comment by paulwe** [comment]
there are no artificial limits and the 3k number may be out of date - there have been a lot of improvements to performance since this benchmark was released. the only way to accurately estimate the single node capacity for your use case is to benchmark your workload on your hardware.

if you need more capacity than a single instance can provide you could load balance your room across multiple servers or check out livekit cloud - https://cloud.livekit.io/ - which does this for you
