### ISSUE TITLE
Handling Sudden Disconnections and Room Termination in LiveKit

### ISSUE THREAD

**Issue by bigmoveus** [livekit/livekit#3292]
If a user unexpectedly closes their browser or app (e.g., due to a crash, force quit, or network issues), does LiveKit automatically detect disconnections and terminate the room? Is there a parameter or mechanism for this? Since such events happen abruptly, it is not feasible to send a request from the client side. Therefore, the server must handle the termination.

**Comment by davidzhao** [comment]
we do detect it.. and that's why you see a `ParticipantDisconnect` event 15s later. It's not possible to reduce that timeout though. Doing so would likely cause other false positives (i.e. user did not disconnect)

If you are looking for a faster metric, take a look at ConnectionQuality updates. We do send a `Lost` update when we haven't heard from the participant in a few seconds

**Comment by bigmoveus** [comment]
Thanks for your help , just What is the webhook event related to ConnectionQuality updates?

**Comment by davidzhao** [comment]
it's not a webhook event, but an event that is sent to everyone in the room. https://docs.livekit.io/home/client/events/#events
