### ISSUE TITLE
How many consumers can be supported per CPU core?

### ISSUE THREAD

**Issue by danielxvu** [livekit/livekit#726]
Hi, would you be able to comment on how LiveKit fares in terms of performance when compared to other SFUs i.e. MediaSoup? [MediaSoup claims to support 500 consumers per CPU core](https://mediasoup.org/documentation/v3/scalability/#multiple-and-separate-mediasoup-routers):

> Depending on the host CPU capabilities, a mediasoup C++ subprocess can typically handle over ~500 consumers in total. If for example there are 4 peers in a room, all them sending audio and video and all them consuming the audio and video of the other peers, this would mean that:
> 
> Each peer receives audio and video from 3 peers, so 3x2 = 6 consumers in total.
> There are 4 peers, so 4x6 = 24 consumers in total.

In particular, the LiveKit blog post[ "Going beyond a single-core"](https://blog.livekit.io/going-beyond-a-single-core-4a464d20d17a/) seems to imply that the number of 1600 down-tracks equates to the number of video tracks being consumed. If this assumption is correct, then 1600 video tracks divided by 16 cores comes out to 100 per core. Is the takeaway from said article then that LiveKit, on a 16-core VM, can only handle up to 100 consumers per core before experiencing performance degradation? And do the recent improvements cited in ["Bringing Zoom's end-to-end optimizations to WebRTC"](https://blog.livekit.io/livekit-one-dot-zero/) possibly improve the situation here?

**Comment by davidzhao** [comment]
As noted in the blog post, LiveKit uses a multicore architecture so we are not limited to using a single core. We don't quote a simple "it can support N consumers" because the answer depends on what the consumers are doing. As an example, in [last set of benchmarks](https://docs.livekit.io/deploy/benchmark/#benchmarks) we performed, a 16-core instance is capable of handling:
* 1 publisher publishing audio and 720p video, 3000 subscribers - 3,000 consumers
* 10 publishers publishing audio, 3000 subscribers - 30,000 consumers

In many cases, network becomes a bottleneck before CPU does. (3000 720p videos would be pushing 5Gbps)

When it comes down to raw CPU performance, I would think mediasoup is likely more optimized given its written in C++. We are more focused on achieving end-to-end efficiencies and enabling applications to achieve their use cases by spreading the load across cores & instances.
